language: c++
dist: bionic
before_install:
  - sudo apt-get update
  - sudo apt-get install -y cmake gcc-avr binutils-avr avr-libc
  - pip install --user cpp-coveralls

jobs:
  include:
    - stage: "Linux target"
      name: "Linux target"
      compiler: gcc
      script:
        - mkdir build_linux
        - cd build_linux 
        - cmake  ../ -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DWITH_COVERAGE=TRUE
        - cmake --build . && ctest
      after_success:
        - coveralls --exclude CMakeFiles/ --gcov-options '\-lp'
    - stage: "AVR target"
      name: "AVR target"
      compiler: avr-gcc
      script:
        - mkdir build_avr
        - cd build_avr
        - sh ../scripts/init-avr-linux.sh
        - cmake --build .
